CREATE TABLE "Despensas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Despensas" PRIMARY KEY ("Id")
);


CREATE TABLE "Produtos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(200) NOT NULL,
    "Marca" character varying(100),
    "CodigoBarras" character varying(50),
    "Categoria" character varying(50),
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id")
);


CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Email" text NOT NULL,
    "SenhaHash" text,
    "Provider" text,
    "Plano" integer NOT NULL,
    "DataExpiracaoAssinatura" timestamp with time zone,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);


CREATE TABLE "WebhookEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StripeEventId" character varying(255) NOT NULL,
    "EventType" character varying(100) NOT NULL,
    "ProcessadoEm" timestamp with time zone NOT NULL,
    "ProcessadoComSucesso" boolean NOT NULL,
    "ErroProcessamento" character varying(1000),
    "PayloadCompleto" text,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WebhookEvents" PRIMARY KEY ("Id")
);


CREATE TABLE "EstoqueItens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DespensaId" integer NOT NULL,
    "ProdutoId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "QuantidadeMinima" integer NOT NULL,
    "DataValidade" timestamp with time zone,
    "Preco" numeric(10,2),
    "DataAdicao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EstoqueItens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EstoqueItens_Despensas_DespensaId" FOREIGN KEY ("DespensaId") REFERENCES "Despensas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EstoqueItens_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AssinaturasStripe" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "StripeSubscriptionId" character varying(255) NOT NULL,
    "StripeCustomerId" character varying(255) NOT NULL,
    "PlanId" character varying(100) NOT NULL,
    "Status" integer NOT NULL,
    "DataInicio" timestamp with time zone NOT NULL,
    "DataCancelamento" timestamp with time zone,
    "ProximaCobranca" timestamp with time zone NOT NULL,
    "FimPeriodoAtual" timestamp with time zone NOT NULL,
    "Valor" numeric NOT NULL,
    "Moeda" character varying(3) NOT NULL,
    "Intervalo" character varying(50),
    "CanceladaFimPeriodo" boolean NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataAtualizacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssinaturasStripe" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssinaturasStripe_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ConvitesDespensa" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DespensaId" integer NOT NULL,
    "RemetenteId" integer NOT NULL,
    "DestinatarioId" integer NOT NULL,
    "Mensagem" text,
    "DataEnvio" timestamp with time zone NOT NULL,
    "DataResposta" timestamp with time zone,
    "Estado" integer NOT NULL,
    CONSTRAINT "PK_ConvitesDespensa" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConvitesDespensa_Despensas_DespensaId" FOREIGN KEY ("DespensaId") REFERENCES "Despensas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConvitesDespensa_Usuarios_DestinatarioId" FOREIGN KEY ("DestinatarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ConvitesDespensa_Usuarios_RemetenteId" FOREIGN KEY ("RemetenteId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ListaDeComprasItens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "ProdutoId" integer,
    "DescricaoManual" text,
    "QuantidadeDesejada" integer NOT NULL,
    "Comprado" boolean NOT NULL,
    "DataCompra" timestamp with time zone,
    "DataCriacao" timestamp with time zone NOT NULL,
    "PrecoEstimado" numeric(10,2),
    "Loja" text,
    "Notas" text,
    CONSTRAINT "PK_ListaDeComprasItens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ListaDeComprasItens_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ListaDeComprasItens_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MembrosDespensa" (
    "UsuarioId" integer NOT NULL,
    "DespensaId" integer NOT NULL,
    "Papel" integer NOT NULL,
    "DataAcesso" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MembrosDespensa" PRIMARY KEY ("UsuarioId", "DespensaId"),
    CONSTRAINT "FK_MembrosDespensa_Despensas_DespensaId" FOREIGN KEY ("DespensaId") REFERENCES "Despensas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MembrosDespensa_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "HistoricosDeConsumo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EstoqueItemId" integer NOT NULL,
    "QuantidadeConsumida" integer NOT NULL,
    "DataDoConsumo" timestamp with time zone NOT NULL,
    "UsuarioId" integer NOT NULL,
    "QuantidadeRestanteAposConsumo" integer NOT NULL,
    "DiaSemanaDaConsumo" integer NOT NULL,
    "HoraDaConsumo" integer NOT NULL,
    CONSTRAINT "PK_HistoricosDeConsumo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistoricosDeConsumo_EstoqueItens_EstoqueItemId" FOREIGN KEY ("EstoqueItemId") REFERENCES "EstoqueItens" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HistoricosDeConsumo_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "PagamentosHistorico" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SubscricaoStripeId" integer NOT NULL,
    "StripeInvoiceId" character varying(255) NOT NULL,
    "StripePaymentIntentId" character varying(255),
    "Valor" numeric NOT NULL,
    "Moeda" character varying(3) NOT NULL,
    "Status" integer NOT NULL,
    "DataPagamento" timestamp with time zone NOT NULL,
    "DataProcessamento" timestamp with time zone,
    "MotivoFalha" character varying(500),
    "CodigoFalha" character varying(100),
    "TentativasRetry" integer NOT NULL,
    "ProximaTentativa" timestamp with time zone,
    "InicioPeriodo" timestamp with time zone NOT NULL,
    "FimPeriodo" timestamp with time zone NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PagamentosHistorico" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PagamentosHistorico_AssinaturasStripe_SubscricaoStripeId" FOREIGN KEY ("SubscricaoStripeId") REFERENCES "AssinaturasStripe" ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_AssinaturasStripe_StripeSubscriptionId" ON "AssinaturasStripe" ("StripeSubscriptionId");


CREATE INDEX "IX_SubscricaoStripe_Usuario_Status" ON "AssinaturasStripe" ("UsuarioId", "Status");


CREATE UNIQUE INDEX "IX_ConvitesDespensa_DespensaId_DestinatarioId_Estado" ON "ConvitesDespensa" ("DespensaId", "DestinatarioId", "Estado") WHERE "Estado" = 0;


CREATE INDEX "IX_ConvitesDespensa_DestinatarioId" ON "ConvitesDespensa" ("DestinatarioId");


CREATE INDEX "IX_ConvitesDespensa_RemetenteId" ON "ConvitesDespensa" ("RemetenteId");


CREATE INDEX "IX_EstoqueItens_DespensaId" ON "EstoqueItens" ("DespensaId");


CREATE INDEX "IX_EstoqueItens_ProdutoId" ON "EstoqueItens" ("ProdutoId");


CREATE INDEX "IX_HistoricoConsumo_Data" ON "HistoricosDeConsumo" ("DataDoConsumo");


CREATE INDEX "IX_HistoricoConsumo_EstoqueItem_Data" ON "HistoricosDeConsumo" ("EstoqueItemId", "DataDoConsumo");


CREATE INDEX "IX_HistoricosDeConsumo_UsuarioId" ON "HistoricosDeConsumo" ("UsuarioId");


CREATE INDEX "IX_ListaDeComprasItens_ProdutoId" ON "ListaDeComprasItens" ("ProdutoId");


CREATE INDEX "IX_ListaDeComprasItens_UsuarioId" ON "ListaDeComprasItens" ("UsuarioId");


CREATE INDEX "IX_MembrosDespensa_DespensaId" ON "MembrosDespensa" ("DespensaId");


CREATE INDEX "IX_PagamentoHistorico_Subscricao_Data" ON "PagamentosHistorico" ("SubscricaoStripeId", "DataPagamento");


CREATE UNIQUE INDEX "IX_PagamentosHistorico_StripeInvoiceId" ON "PagamentosHistorico" ("StripeInvoiceId");


CREATE UNIQUE INDEX "IX_Produtos_CodigoBarras" ON "Produtos" ("CodigoBarras");


CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");


CREATE INDEX "IX_WebhookEvent_Type_Processed" ON "WebhookEvents" ("EventType", "ProcessadoEm");


CREATE UNIQUE INDEX "IX_WebhookEvents_StripeEventId" ON "WebhookEvents" ("StripeEventId");


