// <auto-generated />
using System;
using EstoqueApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstoqueApp.Api.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20250709144414_TemporaryStringDateFields")]
    partial class TemporaryStringDateFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstoqueApp.Api.Models.ConviteDespensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DespensaId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("DespensaId", "DestinatarioId", "Estado")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 0");

                    b.ToTable("ConvitesDespensa");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Despensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Despensas");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.EstoqueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataAdicaoString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataValidadeString")
                        .HasColumnType("text");

                    b.Property<int>("DespensaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DespensaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("EstoqueItens");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.HistoricoConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDoConsumo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemanaDaConsumo")
                        .HasColumnType("integer");

                    b.Property<int>("EstoqueItemId")
                        .HasColumnType("integer");

                    b.Property<int>("HoraDaConsumo")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeConsumida")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeRestanteAposConsumo")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataDoConsumo")
                        .HasDatabaseName("IX_HistoricoConsumo_Data");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstoqueItemId", "DataDoConsumo")
                        .HasDatabaseName("IX_HistoricoConsumo_EstoqueItem_Data");

                    b.ToTable("HistoricosDeConsumo");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ListaDeComprasItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Comprado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoManual")
                        .HasColumnType("text");

                    b.Property<string>("Loja")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDesejada")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListaDeComprasItens");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.MembroDespensa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("DespensaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "DespensaId");

                    b.HasIndex("DespensaId");

                    b.ToTable("MembrosDespensa");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.PagamentoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoFalha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FimPeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioPeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ProximaTentativa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SubscricaoStripeId")
                        .HasColumnType("integer");

                    b.Property<int>("TentativasRetry")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("SubscricaoStripeId", "DataPagamento")
                        .HasDatabaseName("IX_PagamentoHistorico_Subscricao_Data");

                    b.ToTable("PagamentosHistorico");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanceladaFimPeriodo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FimPeriodoAtual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intervalo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ProximaCobranca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Status")
                        .HasDatabaseName("IX_SubscricaoStripe_Usuario_Status");

                    b.ToTable("AssinaturasStripe");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataExpiracaoAssinatura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plano")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErroProcessamento")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadCompleto")
                        .HasColumnType("text");

                    b.Property<bool>("ProcessadoComSucesso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.HasIndex("EventType", "ProcessadoEm")
                        .HasDatabaseName("IX_WebhookEvent_Type_Processed");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ConviteDespensa", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("Convites")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Destinatario")
                        .WithMany("ConvitesRecebidos")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Remetente")
                        .WithMany("ConvitesEnviados")
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.EstoqueItem", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("EstoqueItens")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.HistoricoConsumo", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.EstoqueItem", "EstoqueItem")
                        .WithMany()
                        .HasForeignKey("EstoqueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstoqueItem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ListaDeComprasItem", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("ListaDeCompras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.MembroDespensa", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("Membros")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("AcessosDespensa")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.PagamentoHistorico", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.SubscricaoStripe", "SubscricaoStripe")
                        .WithMany("Pagamentos")
                        .HasForeignKey("SubscricaoStripeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscricaoStripe");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Despensa", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("EstoqueItens");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Usuario", b =>
                {
                    b.Navigation("AcessosDespensa");

                    b.Navigation("Assinaturas");

                    b.Navigation("ConvitesEnviados");

                    b.Navigation("ConvitesRecebidos");

                    b.Navigation("ListaDeCompras");
                });
#pragma warning restore 612, 618
        }
    }
}
