// <auto-generated />
using System;
using EstoqueApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueApp.Api.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    partial class EstoqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EstoqueApp.Api.Models.ConviteDespensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("TEXT");

                    b.Property<int>("DespensaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("DespensaId", "DestinatarioId", "Estado")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 0");

                    b.ToTable("ConvitesDespensa");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Despensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Despensas");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.EstoqueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("DespensaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DespensaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("EstoqueItens");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.HistoricoConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDoConsumo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemanaDaConsumo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstoqueItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraDaConsumo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeConsumida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRestanteAposConsumo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataDoConsumo")
                        .HasDatabaseName("IX_HistoricoConsumo_Data");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstoqueItemId", "DataDoConsumo")
                        .HasDatabaseName("IX_HistoricoConsumo_EstoqueItem_Data");

                    b.ToTable("HistoricosDeConsumo");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ListaDeComprasItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Comprado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoManual")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeDesejada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListaDeComprasItens");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.MembroDespensa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DespensaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("TEXT");

                    b.Property<int>("Papel")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "DespensaId");

                    b.HasIndex("DespensaId");

                    b.ToTable("MembrosDespensa");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.PagamentoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoFalha")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FimPeriodo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioPeriodo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaTentativa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscricaoStripeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativasRetry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("SubscricaoStripeId", "DataPagamento")
                        .HasDatabaseName("IX_PagamentoHistorico_Subscricao_Data");

                    b.ToTable("PagamentosHistorico");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanceladaFimPeriodo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FimPeriodoAtual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intervalo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProximaCobranca")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Status")
                        .HasDatabaseName("IX_SubscricaoStripe_Usuario_Status");

                    b.ToTable("AssinaturasStripe");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataExpiracaoAssinatura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Plano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErroProcessamento")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadCompleto")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProcessadoComSucesso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.HasIndex("EventType", "ProcessadoEm")
                        .HasDatabaseName("IX_WebhookEvent_Type_Processed");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ConviteDespensa", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("Convites")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Destinatario")
                        .WithMany("ConvitesRecebidos")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Remetente")
                        .WithMany("ConvitesEnviados")
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.EstoqueItem", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("EstoqueItens")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.HistoricoConsumo", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.EstoqueItem", "EstoqueItem")
                        .WithMany()
                        .HasForeignKey("EstoqueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstoqueItem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.ListaDeComprasItem", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("ListaDeCompras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.MembroDespensa", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Despensa", "Despensa")
                        .WithMany("Membros")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("AcessosDespensa")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.PagamentoHistorico", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.SubscricaoStripe", "SubscricaoStripe")
                        .WithMany("Pagamentos")
                        .HasForeignKey("SubscricaoStripeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscricaoStripe");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.HasOne("EstoqueApp.Api.Models.Usuario", "Usuario")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Despensa", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("EstoqueItens");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.SubscricaoStripe", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("EstoqueApp.Api.Models.Usuario", b =>
                {
                    b.Navigation("AcessosDespensa");

                    b.Navigation("Assinaturas");

                    b.Navigation("ConvitesEnviados");

                    b.Navigation("ConvitesRecebidos");

                    b.Navigation("ListaDeCompras");
                });
#pragma warning restore 612, 618
        }
    }
}
